---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Release.Name }}
 labels:
  app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
          - name: httpport
            containerPort: {{ .Values.image.port }}
          livenessProbe:
            httpGet:
              path: "/login"
              port: {{ .Values.image.port }}
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: {{ .Values.image.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
    #       volumeMounts:
    #       - name:  jenkins-data
    #         mountPath:  /var/jenkins_home
    #   volumes:
    #     - name: jenkins-data
    #       persistentVolumeClaim:
    #         claimName: {{ .Values.pvcClaimName }}
